image: node:16

before_script:
  - export TZ='Asia/Shanghai'
  - git config --global user.name "coolrc136"
  - git config --global user.email "root@coolrc.me"
  - npm install -g hexo-cli
  - npm install

pages:
  cache:
    paths:
    - node_modules/

  script:
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master

